### ISSUE TITLE
Doesn't Seem to Collect Replies to a Tweet

### ISSUE THREAD

**Issue by greenwoodma** [digitalmethodsinitiative/zeeschuimer#10]
If you view the web page of a single tweet and scroll through the replies it appears that no data is collected. Looking at the network history in the browser developer console it looks as if the data comes via a URL of the form `https://twitter.com/i/api/graphql/<random string>/TweetDetail`. Looking at the source code for the plugin `TweetDetail` doesn't seem to be one of the URL checks. Not sure if just adding that check would be enough or if the format of the response is too different etc. Will try and check myself but thought I'd raise it now given I currently only have a released version installed and so am not immediately set up to debug/develop.

**Comment by stijn-uva** [comment]
As far as I can see this was fixed in one of the previous updates.
