### ISSUE TITLE
Links shared on Linkedin

### ISSUE THREAD

**Issue by kolenyo2099** [digitalmethodsinitiative/zeeschuimer#12]
While this is an incredible and amazing tool and I'm highly grateful to the developers, it does not seem to collect the links that people share in their LinkedIn posts. It does collect the text and the images, but links to pdfs or other websites not.

**Comment by stijn-uva** [comment]
This is an issue in 4CAT rather than Zeeschuimer, as this information is in the collected data but not mapped by 4CAT for its CSV export. So I'm closing it here, but we will address it in 4CAT.
