### ISSUE TITLE
Missing TikTok data

### ISSUE THREAD

**Issue by hnasbo** [digitalmethodsinitiative/zeeschuimer#23]
Hello there!
I am collecting TikTok data, and I continuously get datasets that miss the first 30-40 TikToks. I re-runned it a few times, and then once in a while I can actually collect all, but it is rather unpredictable. Is there a way to fix this? Thank you in advance!

**Comment by dale-wahl** [comment]
Which pages specifically are you having the issue with?

**Comment by hnasbo** [comment]
Thank you so much for the super quick response! For example on this profile: https://www.tiktok.com/@ladyszomjas
Every time, the data is collected starting from: https://www.tiktok.com/@ladyszomjas/video/7281986300348026145

**Comment by dale-wahl** [comment]
Thanks, will take a look

**Comment by dale-wahl** [comment]
I confirmed your issue. For the moment, if you right click the page and select "View Page Source", Zeeschuimer will collect those first results as well. We'll work on a proper fix.

**Comment by hnasbo** [comment]
Thank you very much! This already solves the problem for me now.

**Comment by stijn-uva** [comment]
Fixed in #24, thanks for reporting!
