### ISSUE TITLE
Linkedin Sales Navigator

### ISSUE THREAD

**Issue by TristanvanDoorn** [digitalmethodsinitiative/zeeschuimer#25]
Ha Stijn,

het zou geweldig zijn wanneer Linkedin Sales Navigator kan worden toegevoegd. Sales Navigator heeft veel en veel meer opties tot filtering, waardoor het aantal relevante posts en daarmee bruikbare data behoorlijk kan toenemen.

**Comment by stijn-uva** [comment]
This is not currently a priority, as Linkedin Sales Navigator is only accessible through a paid LinkedIn plan.
