### ISSUE TITLE
Zeeschuimer only captures data from "For you page", and nothing from a user's page

### ISSUE THREAD

**Issue by reginagal** [digitalmethodsinitiative/zeeschuimer#26]
Dear @stijn-uva !

I have the following problem. No matter how long I scroll, or how long I wait, Zeeschuimer only saves the posts and their details from my  Foryoupage on Instagram. In my thesis I'm analysing Instagram posts, and for this I would need the posts of specific users. I think it is likely that Instagram has updated its interface and Zeeschuimer no longer recognizes the posts in any other view than "frontpage" or "For You" page. 

Could you please help me with this?

**Comment by stijn-uva** [comment]
Thanks for reporting! This is fixed in the new release. Zeeschuimer should automatically update within 24 hours of the release, or you can download the new version yourself.

**Comment by reginagal** [comment]
Thank you so much for the quick response! Everything is perfect now!
