### ISSUE TITLE
TikTok video_url maybe need token

### ISSUE THREAD

**Issue by dale-wahl** [digitalmethodsinitiative/zeeschuimer#4]
Trying to download the links output to the video_url field and having an issue with the majority.  It seems that links in this format work:
`https://v16m-webapp.tiktokcdn-us.com/a5f9e55857d5db62a3ebba484739bed4/63924705/video/tos/alisg/tos-alisg-pve-0037c001/o4bTCdKE8jmYQgDxlVPeZEfnBEU8hoRPoPQAgB/?a=1988&ch=0&cr=0&dr=0&lr=tiktok_m&cd=0%7C0%7C1%7C0&cv=1&br=3904&bt=1952&cs=0&ds=3&ft=ebtHKH-qMyq8ZpuyShe2Nom~fl7Gb&mime_type=video_mp4&qs=0&rc=NTk6OTU1aGllOmc0Nzw7OUBpM2hkZjo6Zjd2aDMzODczNEAxXmI2YDIvNTMxNGNhLjUwYSNzY21qcjRvaDBgLS1kMS1zcw%3D%3D&l=2022120814193899017DE6214470059B7C`
While links in this format return a 403 Forbidden error:
`https://v16-webapp-prime.us.tiktok.com/video/tos/useast2a/tos-useast2a-pve-0068/owRNRjLvjuVDEDYnBAUEeNwbVxbQmeInQPJBVQ/?a=1988&ch=0&cr=0&dr=0&lr=tiktok_m&cd=0%7C0%7C1%7C0&cv=1&br=2812&bt=1406&cs=0&ds=3&ft=ebLH6H-qMyq8Zn.yShe2N03ufl7Gb&mime_type=video_mp4&qs=0&rc=PDk3ZTxkOWc7OWQ0ZTZoNkBpang1dDk6ZjhqaDMzNzczM0AyMGJgMGNjXjIxYWJhY140YSNeY2tvcjRfbDNgLS1kMTZzcw%3D%3D&expire=1670530563&l=20221208141458BB1C197C6FEECD05291B&policy=2&signature=42c81996a4e72c5814e104b8cf1d8624&tk=tt_chain_token`

I'm guessing that `tt_chain_token` means something. Not sure that there is anything in the response that ZeeSchuimer could lift and provide, but right now I'm not sure how to download the majority of videos (also not sure what causes the different formats). I'm currently not logged in if that makes a difference.

**Comment by dale-wahl** [comment]
It looks like videos can load from two sources `v16-webapp-prime.us.tiktok.com` and `v16m-webapp.tiktokcdn-us.com`.  At least for me right now in the US. If I get the non "prime" one, I'm fine in downloading. I can reload and get different versions it seems.

**Comment by dale-wahl** [comment]
Can we force HTTP version? Seems 2 vs 1.1 may be the deciding factor...

**Comment by dale-wahl** [comment]
I copied all the headers of the browser based request and was able to get a non 403 response via python, but the `v16-webapp-prime.us.tiktok.com` based domain is returning a `206` partial response. Which is what it was doing in the browser so I should not be surprised. Unfortunately, it is not the full video and instead the video appears corrupt. Le sigh.

**Comment by stijn-uva** [comment]
This is very difficult to sustainably address within Zeeschuimer; instead we addressed it by having 4CAT re-fetch the relevant URLs when anything is done with them (e.g. to download videos or images).
