### ISSUE TITLE
Instagram datasource does not collect "Explore" page

### ISSUE THREAD

**Issue by dale-wahl** [digitalmethodsinitiative/zeeschuimer#8]
|Page|Status|Notes|
| -- | -- | -- |
|Home|✔||
|User pages|✔||
|Hashtag pages|✔||
|Explore|❌|A couples posts appear to be collected, but not the vast majority|
|Reels|❌|Reels are a slightly different datatype...|

I noticed the Explore page could not collect results and wanted to compile a quick list for reference.

**Comment by stijn-uva** [comment]
This is unfortunately as intended at the moment, since the explore page (and the reels page) do not provide enough information to reconstruct full post objects from.
