### ISSUE TITLE
Twitter doesn't work

### ISSUE THREAD

**Issue by barripdmx** [digitalmethodsinitiative/zeeschuimer#9]
Hello.
I've tried Twitter and it works by browsing multiple accounts, but nothing is downloaded in the search engine.
There's a solution?

**Comment by stijn-uva** [comment]
Hi @barripdmx , can you please provide a bit more information on what you are trying to do, e.g. whether you are using the Academic or Standard API Track what 4CAT's output is for a query.

Note that Twitter has been limiting access via their API recently and many API tokens no longer work. This is not something we can fix in 4CAT.

**Comment by stijn-uva** [comment]
Hi @barripdmx , thanks for reporting this. This is now fixed by 673bbf84fbeadd8702937f3224945652e161734a. We will make a new release soon which will incorporate the fix.
